[package]
name = "aeronet"
version = "0.1.0"
edition = "2021"
description = "Lightweight client/server network library"
authors = [ "aecsocket <aecsocket@tutanota.com>" ]
repository = "https://github.com/aecsocket/aeronet"
keywords = [ "gamedev", "network", "bevy" ]
categories = [ "game-development", "network-programming" ]
license = "MIT OR Apache-2.0"

[features]
## Enables [`bevy`](https://docs.rs/bevy) support such as Event derives and plugins.
bevy = [ "dep:bevy" ]

## Enables using an async [`tokio`](https://docs.rs/tokio) runtime in a
## [`bevy`](https://docs.rs/bevy) resource.
bevy-tokio-rt = [ "bevy", "dep:tokio" ]

## Allows using [`serde`](https://docs.rs/serde) for message serialization.
serde = [ "dep:serde" ]

## Allows using [`bincode`](https://docs.rs/bincode) as a format for message serialization
## using [`serde`](https://docs.rs/serde).
bincode = [ "serde", "dep:bincode" ]

[dependencies]
thiserror = "1.0.47"
anyhow = "1.0.75"
derivative = "2.2.0"
bevy = { version = "0.11.2", default-features = false, optional = true }
tokio = { version = "1.32.0", default-features = false, features = [ "rt-multi-thread" ], optional = true }
serde = { version = "1.0.188", optional = true }
bincode = { version = "1.3.3", optional = true }

[package.metadata.docs.rs]
all-features = true

[workspace]
resolver = "2"
members = [
    "aeronet_wt_native",
    #"aeronet_wt_wasm",
]
