[workspace]
resolver = "2"
members = [
    "aeronet",
    #"aeronet_channel",
    "aeronet_wt_core",
    "aeronet_wt_core_derive",
    "aeronet_wt_native",
    #"aeronet_wt_wasm",
]

[workspace.package]
version = "0.4.0"
edition = "2021"
authors = [ "aecsocket <aecsocket@tutanota.com>" ]
repository = "https://github.com/aecsocket/aeronet"
keywords = [ "gamedev", "network", "bevy" ]
categories = [ "game-development", "network-programming" ]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
aeronet = { version = "0.4.0", path = "aeronet" }
aeronet_wt_core_derive = { version = "0.4.0", path = "aeronet_wt_core_derive" }
aeronet_wt_core = { version = "0.4.0", path = "aeronet_wt_core" }

derivative = "2.2.0"
tracing = "0.1.40"
thiserror = "1.0.50"
anyhow = "1.0.75"

proc-macro2 = "1.0.69"
syn = "2.0.38"
quote = "1.0.33"

serde = "1.0.190"
bincode = "1.3.3"

tokio = { version = "1.33.0", default-features = false, features = [ "rt-multi-thread" ] }
crossbeam-channel = "0.5.8"
slotmap = "1.0.6"
replace_with = "0.1.7"

bevy = { version = "0.12.0", default-features = false }
bevy_egui = "0.23.0"
