[package]
name = "aeronet"
version = "0.1.0"
edition = "2021"

[features]
bevy = [ "dep:bevy", "dep:derivative" ]

[dependencies]
thiserror = "1.0.47"
anyhow = "1.0.75"
generational-arena = "0.2.9"
bevy = { version = "0.11.2", default-features = false, optional = true }
derivative = { version = "2.2.0", optional = true }

[workspace]
resolver = "2"
members = [
    "aeronet_channel",
]
