[workspace]
resolver = "2"
members = [
    "aeronet",
    "aeronet_derive",
    "aeronet_protocol",
    "aeronet_channel",
    "aeronet_webtransport",
    "aeronet_steam",
]

[workspace.package]
version = "0.5.0"
edition = "2021"
rust-version = "1.76.0"
authors = ["aecsocket <aecsocket@tutanota.com>"]
repository = "https://github.com/aecsocket/aeronet"
keywords = ["gamedev", "network", "bevy"]
categories = ["game-development", "network-programming"]
license = "MIT OR Apache-2.0"

[workspace.lints.rust]
# missing_docs = "warn"
# unused_crate_dependencies = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
module_name_repetitions = "allow"
similar_names = "allow"

[workspace.dependencies]
aeronet = { version = "0.5.0", path = "aeronet" }
aeronet_derive = { version = "0.5.0", path = "aeronet_derive" }
aeronet_protocol = { version = "0.5.0", path = "aeronet_protocol" }
tracing = "0.1.40"
derivative = "2.2.0"
thiserror = "1.0.56"
either = "1.9.0"
slotmap = "1.0.7"
bytes = "1.5.0"
ahash = "0.8.7"
anyhow = "1.0.79"
rand = "0.8.5"
rand_distr = "0.4.3"
integer-encoding = "4.0.0"
static_assertions = "1.1.0"
assert_matches = "1.5.0"
cfg-if = "1.0.0"

bitcode = "0.5.1"
serde = { version = "1.0.197", features = ["derive"] }

proc-macro2 = "1.0.76"
syn = "2.0.48"
quote = "1.0.35"
const_format = "0.2.32"

futures = "0.3.30"
crossbeam-channel = "0.5.11"
tokio = { version = "1.36.0", default-features = false }

bevy_ecs = { version = "0.13.0", default-features = false }
bevy_app = { version = "0.13.0", default-features = false }
bevy = "0.13.0"
bevy_egui = "0.25.0"

xwt = "0.5.0"
xwt-core = "0.2.2"
wtransport = "0.1.10"

js-sys = "0.3.67"
web-sys = "0.3.67"
wasm-bindgen-futures = "0.4.41"

base64 = "0.21.7"
rcgen = "0.12.0"
ring = "0.17.7"
time = "0.3.31"

steamworks = "0.11.0"
