[workspace]
members = [
  "aeronet",
  "aeronet_derive",
  "aeronet_replicon",
  "aeronet_proto",
  "aeronet_channel",
  "aeronet_webtransport",
  #"aeronet_steam",
]
resolver = "2"

[workspace.package]
authors = ["aecsocket <aecsocket@tutanota.com>"]
categories = ["game-development", "network-programming"]
edition = "2021"
keywords = ["gamedev", "network", "bevy"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/aecsocket/aeronet"
rust-version = "1.76.0"
version = "0.5.0"

[workspace.lints.rust]
# missing_docs = "warn"
# unused_crate_dependencies = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"

module_name_repetitions = "allow"
similar_names = "allow"

[workspace.dependencies]
aeronet = { version = "0.5.0", path = "aeronet" }
aeronet_channel = { version = "0.5.0", path = "aeronet_channel" }
aeronet_derive = { version = "0.5.0", path = "aeronet_derive" }
aeronet_proto = { version = "0.5.0", path = "aeronet_proto" }
aeronet_replicon = { version = "0.5.0", path = "aeronet_replicon" }
aeronet_webtransport = { version = "0.5.0", path = "aeronet_webtransport" }

ahash = { version = "0.8.10", default-features = false, features = ["std"] }
anyhow = "1.0.79"
arbitrary = { version = "1.3.2", features = ["derive"] }
assert_matches = "1.5.0"
bimap = "0.6.3"
bitcode = "0.6.0"
bitvec = "1.0.1"
bytes = "1.5.0"
cfg-if = "1.0.0"
clap = { version = "4.5.4", features = ["derive"] }
dashmap = "5.5.3"
derivative = "2.2.0"
either = "1.9.0"
enum_dispatch = "0.3.12"
integer-encoding = "4.0.0"
rand = "0.8.5"
rand_distr = "0.4.3"
replace_with = "0.1.7"
serde = { version = "1.0.197", features = ["derive"] }
slotmap = "1.0.7"
static_assertions = "1.1.0"
thiserror = "1.0.57"
tracing = "0.1.40"

proc-macro2 = "1.0.76"
quote = "1.0.35"
syn = "2.0.48"

crossbeam-channel = "0.5.11"
futures = "0.3.30"
tokio = { version = "1.36.0", default-features = false }

bevy = "0.13.1"
bevy_app = { version = "0.13.1", default-features = false }
bevy_ecs = { version = "0.13.1", default-features = false }
bevy_egui = "0.26.0"
bevy_replicon = "0.24.1"
bevy_time = { version = "0.13.1", default-features = false }

wtransport = "0.1.12"
xwt = "0.6.0"
xwt-core = "0.2.2"

js-sys = "0.3.67"
wasm-bindgen-futures = "0.4.41"
web-sys = "0.3.67"

base64 = "0.22.0"
rcgen = "0.13.0"
ring = "0.17.7"
time = "0.3.31"

steamworks = "0.11.0"
