[package]
name = "aeronet"
version = "0.1.0"
edition = "2021"
description = "Lightweight client/server network library"
authors = [ "aecsocket <aecsocket@tutanota.com>" ]
repository = "https://github.com/aecsocket/aeronet"
keywords = [ "gamedev", "network", "bevy" ]
categories = [ "game-development", "network-programming" ]
license = "MIT OR Apache-2.0"

[features]
bevy = [ "dep:bevy", "dep:derivative" ]

[dependencies]
thiserror = "1.0.47"
anyhow = "1.0.75"
generational-arena = "0.2.9"
bevy = { version = "0.11.2", default-features = false, optional = true }
derivative = { version = "2.2.0", optional = true }

[workspace]
resolver = "2"
members = [
    #"aeronet_channel",
    #"aeronet_h3",
    "aeronet_wtransport",
]
