[workspace]
resolver = "2"
members = [
    "aeronet",
    "aeronet_example",
    "aeronet_derive",
    "aeronet_channel",
    "aeronet_wt_native",
    "aeronet_wt_wasm",
]

[workspace.package]
version = "0.4.1"
edition = "2021"
rust-version = "1.74.0"
authors = [ "aecsocket <aecsocket@tutanota.com>" ]
repository = "https://github.com/aecsocket/aeronet"
keywords = [ "gamedev", "network", "bevy" ]
categories = [ "game-development", "network-programming" ]
license = "MIT OR Apache-2.0"

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
module_name_repetitions = "allow"

[workspace.dependencies]
aeronet = { version = "0.4.1", path = "aeronet" }
aeronet_derive = { version = "0.4.1", path = "aeronet_derive" }
aeronet_example = { version = "0.4.1", path = "aeronet_example" }

derivative = "2.2.0"
tracing = "0.1.40"
thiserror = "1.0.50"
anyhow = "1.0.75"

proc-macro2 = "1.0.69"
syn = "2.0.39"
quote = "1.0.33"
const_format = "0.2.32"

serde = "1.0.192"
bincode = "1.3.3"

tokio = { version = "1.34.0", default-features = false }
futures = "0.3.29"
crossbeam-channel = "0.5.8"
slotmap = "1.0.6"

bevy = { version = "0.12.0", default-features = false }
bevy_egui = "0.24.0"

wtransport = "0.1.8"

wasm-bindgen = "0.2.89"
wasm-bindgen-futures = "0.4.39"
js-sys = "0.3.65"
web-sys = "0.3.66"

base64 = "0.21.5"
rcgen = "0.11.3"
ring = "0.17.5"
time = "0.3.30"
