[package]
name = "aeronet"
description = "Lightweight client/server network library"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
## Enables [`bevy`](https://docs.rs/bevy) support such as Event derives and plugins.
bevy = [ "dep:bevy" ]

## Enables using an async [`tokio`](https://docs.rs/tokio) runtime in a
## [`bevy`](https://docs.rs/bevy) resource.
bevy-tokio-rt = [ "bevy", "dep:tokio" ]

## Allows using [`bincode`](https://docs.rs/bincode) as a format for message serialization
## using [`serde`](https://docs.rs/serde).
bincode = [ "dep:serde", "dep:bincode" ]

[dependencies]
derivative.workspace = true
thiserror.workspace = true
anyhow.workspace = true

serde = { workspace = true, optional = true }
bincode = { workspace = true, optional = true }

bevy = { workspace = true, optional = true }
tokio = { workspace = true, optional = true, default-features = false, features = [ "rt-multi-thread" ] }
