[package]
name = "aeronet"
description = "Lightweight client/server network library"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
## Enables [`bevy`](https://docs.rs/bevy) support.
bevy = ["dep:bevy_ecs", "dep:bevy_app"]

## Provides a `Runtime` implementation based on Bevy's async task pool.
bevy-async = ["bevy", "dep:bevy_tasks", "dep:async-io"]

[dependencies]
aeronet_derive.workspace = true

derivative.workspace = true
thiserror.workspace = true
slotmap.workspace = true
bytes.workspace = true
rand.workspace = true
rand_distr.workspace = true
bitcode.workspace = true
static_assertions.workspace = true

bevy_ecs = { workspace = true, optional = true }
bevy_app = { workspace = true, optional = true }

bevy_tasks = { workspace = true, optional = true }
async-io = { workspace = true, optional = true }

[dev-dependencies]
assert_matches.workspace = true
