[package]
name = "aeronet"
version = "0.3.0"
edition = "2021"
description = "Lightweight client/server network library"
authors = [ "aecsocket <aecsocket@tutanota.com>" ]
repository = "https://github.com/aecsocket/aeronet"
keywords = [ "gamedev", "network", "bevy" ]
categories = [ "game-development", "network-programming" ]
license = "MIT OR Apache-2.0"

[features]
## Enables [`bevy`](https://docs.rs/bevy) support such as Event derives and plugins.
bevy = [ "dep:bevy" ]

## Enables using an async [`tokio`](https://docs.rs/tokio) runtime in a
## [`bevy`](https://docs.rs/bevy) resource.
bevy-tokio-rt = [ "bevy", "dep:tokio" ]

## Allows using [`bincode`](https://docs.rs/bincode) as a format for message serialization
## using [`serde`](https://docs.rs/serde).
bincode = [ "dep:serde", "dep:bincode" ]

[dependencies]
thiserror = "1.0.50"
anyhow = "1.0.75"
derivative = "2.2.0"
bevy = { version = "0.12.0", optional = true, default-features = false }
tokio = { version = "1.33.0", optional = true, default-features = false, features = [ "rt-multi-thread" ] }
serde = { version = "1.0.189", optional = true }
bincode = { version = "1.3.3", optional = true }

[package.metadata.docs.rs]
all-features = true
