[package]
name = "aeronet"
description = "Lightweight client/server network library"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
## Enables [`bevy`](https://docs.rs/bevy) support.
bevy = [ "dep:bevy_ecs", "dep:bevy_app" ]

## Allows storing an async [`tokio`](https://docs.rs/tokio) runtime in a
## [`bevy`](https://docs.rs/bevy) resource.
bevy-tokio-rt = [ "bevy", "dep:tokio" ]

[dependencies]
aeronet_derive.workspace = true

derivative.workspace = true
slotmap.workspace = true
rand.workspace = true
rand_distr.workspace = true

bevy_ecs = { workspace = true, optional = true }
bevy_app = { workspace = true, optional = true }

tokio = { workspace = true, optional = true, default-features = false, features = [ "rt-multi-thread" ] }
