[package]
name = "aeronet_webtransport_wasm"
version = "0.1.0"
edition = "2021"
description = "WASM WebTransport transport implementation for aeronet"
authors = [ "aecsocket <aecsocket@tutanota.com>" ]
repository = "https://github.com/aecsocket/aeronet"
keywords = [ "gamedev", "network", "bevy" ]
categories = [ "game-development", "network-programming" ]
license = "MIT OR Apache-2.0"

[lib]
crate-type = [ "cdylib", "rlib" ]

[features]
bevy = [ "dep:bevy", "aeronet/bevy" ]
serde = [ "dep:serde", "aeronet/serde" ]

[dependencies]
aeronet = { path = "..", version = "0.1.0" }
log = "0.4.20"
tracing = "0.1.37"
thiserror = "1.0.47"
bevy = { version = "0.11.3", default-features = false, optional = true }
serde = { version = "1.0.188", optional = true }
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.64", features = [
    "WebTransport",
    "WebTransportBidirectionalStream",
    "WebTransportCloseInfo",
    "WebTransportCongestionControl",
    "WebTransportDatagramDuplexStream",
    "WebTransportError",
    "WebTransportErrorOptions",
    "WebTransportErrorSource",
    "WebTransportHash",
    "WebTransportOptions",
    "WebTransportReceiveStream",
    "ReadableStream",
    "WritableStream",
    "ReadableStreamDefaultReader",
    "WritableStreamDefaultWriter",
] }
