[package]
name = "aeronet_wt_native"
version = "0.2.0"
edition = "2021"
description = "Native WebTransport transport implementation for aeronet"
authors = [ "aecsocket <aecsocket@tutanota.com>" ]
repository = "https://github.com/aecsocket/aeronet"
keywords = [ "gamedev", "network", "bevy" ]
categories = [ "game-development", "network-programming" ]
license = "MIT OR Apache-2.0"

[features]
bevy = [ "dep:bevy", "aeronet/bevy" ]

[dependencies]
aeronet = { path = "..", version = "0.2.0", features = [ "bevy-tokio-rt" ] }
aeronet_wt_core = { path = "../aeronet_wt_core", version = "0.2.0" }
tracing = "0.1.37"
thiserror = "1.0.47"
anyhow = "1.0.75"
rustc-hash = "1.1.0"
bevy = { version = "0.11.3", default-features = false, optional = true }
wtransport = { version = "0.1.6", features = [ "dangerous-configuration" ] }
tokio = { version = "1.32.0", default-features = false, features = [ "rt" ] }

[dev-dependencies]
base64 = "0.21.0"
rcgen = "0.11.1"
ring = "0.17.0"
time = "0.3.21"
bevy = "0.11.3"
bevy_egui = "0.22.0"
# todo remove this
aeronet_wt_core_derive = { path = "../aeronet_wt_core_derive" }

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "echo_client"
path = "examples/echo_client.rs"
required-features = [ "bevy" ]

[[example]]
name = "echo_server"
path = "examples/echo_server.rs"
required-features = [ "bevy" ]
