[package]
name = "aeronet_channel"
version = "0.1.0"
edition = "2021"
description = "In-memory MPSC channel transport implementation for aeronet"
authors = [ "aecsocket <aecsocket@tutanota.com>" ]
repository = "https://github.com/aecsocket/aeronet"
keywords = [ "gamedev", "network", "bevy" ]
categories = [ "game-development", "network-programming" ]
license = "MIT OR Apache-2.0"

[features]
bevy = [ "dep:bevy", "aeronet/bevy" ]

[dependencies]
aeronet = { path = "..", version = "0.1.0" }
tracing = "0.1.37"
thiserror = "1.0.47"
anyhow = "1.0.75"
rustc-hash = "1.1.0"
crossbeam-channel = "0.5.8"
bevy = { version = "0.11.2", default-features = false, optional = true }

[package.metadata.docs.rs]
all-features = true
