[package]
name = "aeronet_channel"
version = "0.1.0"
edition = "2021"
description = "Crossbeam MPSC channel transport for aeronet"
authors = [ "aecsocket <aecsocket@tutanota.com>" ]
repository = "https://github.com/aecsocket/aeronet"
keywords = [ "gamedev", "network", "bevy" ]
categories = [ "game-development", "network-programming" ]
license = "MIT OR Apache-2.0"

[features]
bevy = [ "aeronet/bevy", "dep:bevy" ]

[dependencies]
aeronet = { path = "..", version = "0.1.0" }
thiserror = "1.0.47"
anyhow = "1.0.75"
derivative = "2.2.0"
bevy = { version = "0.11.2", default-features = false, optional = true }

crossbeam-channel = "0.5.8"

[[example]]
name = "echo"
path = "examples/echo.rs"
required-features = [ "bevy" ]
